PPO + JAX + EnvPool + Atari (#227)
* PPO + jax + envpool + atari

* fix bug: only report metric when lifes are used up

* pre-commit

* quick fix

* Quick refactor

* push changes

* pre-commit and use EnvPool's new API

* update envpool

* update docs

* update ppo benchmark script

* update docs

* use the latest envpool interface

* update envpool to the latest version

* update pyproject.toml

* update lock files

* Quick clarification

* Update docs

* remove non benchmarked script

* update docs

* revert poetry changes

* docs fix

* remove uncessary code, add docs

* add a note one envpool

* update test cases

* explain `get_action_and_value`

* fix indent

* Fix weird error with `np.mean`. See below:

We got this message. See https://github.com/vwxyzjn/cleanrl/pull/227#discussion_r969129061
```
NotImplementedError: Got <class 'jaxlib.xla_extension.DeviceArray'>, but numpy array, torch tensor, or caffe2 blob name are expected.
```

* update docs

* pre-commit

* add note on `charts/avg_episodic_return`

* update reproducibility script

* add note on value function clipping