Depreciate legacy constructor so that cuda can be used
Here's an error I got when running this code on cuda:
```
>>> import torch
>>> torch.FloatTensor((1 - 0) / 2.0, device="cuda:0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: legacy constructor expects device type: cpu but device type: cuda was passed
```